name: BlockBreaker-Bungee
version: 1.2
author: lusu007
main: me.lusu007.blockbreaker_bungeecord.BungeeCordMain

commands:
  broadcast:
    description: Sendet eine Nachricht an alle Spieler und Server
  wartung:
    aliases: [wa]
    description: Setzt den Server in den Wartungsmodus
  hub:
    description: Teleportiert dich auf die Lobby
    usage: /hub
  unban:
    description: Unbannt einen Spieler
    usage: /unban <Spieler>
  ban:
    description: Bannt einen Spieler permanent
    usage: /ban <Spieler>
  tempban:
    description: Bannt einen Spieler temporär
    usage: /tempban <Spieler> <Länge> <Einheit>
  check:
    description: Checkt ob ein SPieler gebannt ist
    usage: /check <Spieler>

permissions:
  server.broadcast:
    default: false
  server.maintenance.join:
    default: false
  server.maintenance.set:
    default: false
  server.command.hub:
    default: false
  server.ban.check:
    default: false
  server.ban.ban:
    default: false
  server.ban.tempban:
    default: false
  server.ban.unban:
    default: false