name: BlockBreaker-Bungee
version: 1.0
author: lusu007
main: me.lusu007.blockbreaker_bungeecord.BungeeCordMain

commands:
  broadcast:
    description: Sendet eine Nachricht an alle Spieler und Server
  wartung:
    aliases: [wa]
    description: Setzt den Server in den Wartungsmodus
  hub:
    description: Teleportiert dich auf die Lobby
    usage: /hub

permissions:
  server.broadcast:
    default: false
  server.maintenance.join:
    default: false
  server.maintenance.set:
    default: false
  server.command.hub:
    default: false